version: "3.9"
services:
    web:
        build:
            context: typescript
            dockerfile: simple-mercari-web/dockerfile
        ports:
            - "3000:3000"
    app:
        build:
            context: .
            dockerfile: python/dockerfile
        ports:
            - "9000:9000"
