# syntax=docker/dockerfile:1
FROM python:3.9.12-bullseye

WORKDIR /app
COPY db db
COPY image image
WORKDIR python
COPY ./python/requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY python .
EXPOSE 9000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9000"]
